### ISSUE TITLE
¿Nombre de los métodos en mayúscula?

### ISSUE THREAD

**Issue by efren-cabrera** [IslasGECI/ejemplo_typescript#1]
@evaristor ¿Ahora ponen los nombres de os métodos en mayúscula o solo porque estos son estáticos? (Solo lo pregunto porque estaba viendo en dónde podía colaborar con ustedes y no veo ninguna guía de estilo)

https://github.com/IslasGECI/ejemplo_typescript/blob/b660d9c215298f0a99516cb65649a473e3a79898/src/Calculator.ts#L2

**Comment by devarops** [comment]
Todavía no adoptamos guía de estilo para Typescript. Apenas estamos intentando correr Stryker con GitHub Actions, pero aún no lo hemos logrado

**Comment by devarops** [comment]
Checa, @efren-cabrera, [esto](https://github.com/IslasGECI/ejemplo_typescript/runs/456764219) es con lo que estamos batallando

**Comment by devarops** [comment]
Este ejemplo sólo pretende echar a andar Stryker. En este caso no nos preocuparemos por mayúsculas o minúsculas.
