### ISSUE TITLE
Implementa mutation testing mediante Stryker

### ISSUE THREAD

**Issue by devarops** [IslasGECI/ejemplo_typescript#2]
- [x] Quitar el _workflow_ de CI
- Tratar de reproducir la estructura de Rupany a la de Gatsby:
  - [ ] Queremos que lo que está en el _workspace_  `mumbling` esté la raíz de este repo.

**Comment by devarops** [comment]
El @nepito y yo lo estamos trabajando en los EvatisTomates. Ya están andando en GitHub Actions con código de terceros. Ahora estamos convirtiendo el ejemplo a su mínima expresión.

**Comment by devarops** [comment]
Ahora estamos intentando con Jest. Las pruebas ya están corriendo, falta usar el ejemplo de Kepler.

**Comment by nepito** [comment]
La [liga](https://github.com/ChiragRupani/TSUnitTestsSetup) del Rupani

**Comment by nepito** [comment]
[Aquí](https://github.com/IslasGECI/ejemplo_typescript/issues/6) están los pendientes. Y son:
- Quitar el _workflow_ de CI
- Tratar de reproducir la estructura de Rupany a la de Gatsby

**Comment by nepito** [comment]
Esta es la [liga](https://gitlab.com/nepito/code_war) del repo `code_wars` donde ya está corriendo Striker con la configuración mínima. 

Queremos que lo que está en la _workspace_ `mumbling` esté en la raiz de este (`ejemplo_typescript`) repo.
