### ISSUE TITLE
Implementar `jest`

### ISSUE THREAD

**Issue by nepito** [IslasGECI/ejemplo_typescript#3]
El siguiente paso es copiar lo que hay en esta [carpeta](https://github.com/ChiragRupani/TSUnitTestsSetup/tree/master/HelloJest), para implementar `jest`.

**Comment by devarops** [comment]
Vamos creando un _pr_  de lo que estamos haciendo en evaristomates

**Comment by nepito** [comment]
Ya quedó [aquí](https://github.com/IslasGECI/ejemplo_typescript/runs/693965691?check_suite_focus=true) lo puedes ver.
