### ISSUE TITLE
Correr `Calculator` como lo hace Kepler

### ISSUE THREAD

**Issue by nepito** [IslasGECI/ejemplo_typescript#5]
Puse los archivo de Chirag en las carpetas de Kepler y aun no corre. Creemos que los errores pueden ser:
- [x] Que el `jest` no está considerando que `Calculador` es un módulo
- [x] Otra opción es trar de correr `striker` en las carpetas de Rupani
# Referencias
- [Chirag Rupani](https://github.com/ChiragRupani/TSUnitTestsSetup/tree/master/HelloJest)

**Comment by nepito** [comment]
Estos pendientes los estamos atendiendo en el [repo](https://github.com/nepito/gatsby-theme-atom-service) personal del nepo

**Comment by devarops** [comment]
¿Existe un _PR_ asociado a este _issue_?
